### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by mariamm20**
I think without the ' . ' look nice. I hope you accept it

### CODE REVIEW

**Review by EmilyHolland25 — APPROVED** [review]
I agree, thanks!

**Comment by mariamm20** [comment]
I just want to ask about sth. Just because I contribute on the same branch "main" you can not merge it ?

**Comment by EmilyHolland25** [comment]
Sorry I’m new to github and wasn’t sure how to merge it, think I’ve done it now tho

**Comment by mariamm20** [comment]
Thank you ❤

**Pull request merged**
